# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Runs HyperTraPS-related inference on a dataset of observations
#'
#' @param matrix A matrix of observations. Should contain 0s, 1s, and optional 2s for missing data. Should be $n \times L$, containing $n$ cross-sectional observations of length $L$.
#' @param initialstates An optional matrix of initial states. If we are using longitudinal observations, each row in this matrix gives the "before" state to the corresponding "after" state in the observations matrix. Omitting this matrix is equivalent to consider every observation to have a root "before" state. If specified, should be $n \times L$, containing $n$ cross-sectional observations of length $L$, to match the observations matrix.
#' @param start_times An optional vector of $n$ times describing the beginning of the observation time window for each observation. If empty, equivalent to this time window beginning at time 0. If specified, should be of length $n$.
#' @param end_times An optional vector of $n$ times describing the end of the observation time window for each observation. If empty, equivalent to this time window ending at time infinity. If specified, should be of length $n$.
#' @param length_index Length of MCMC chain
#' @param kernel_index Kernel index
#' @param losses Whether to consider accumulation of gains (0) or losses (1)
#' @param apm_type APM
#' @param sgd_scale SGD
#' @param seed Random number seed
#' @param outputinput Option to output the input data
#' @param regularise Regularise
#' @param model Model structure
#' @param pli Phenotype landscape inference
#' @return A named list of objects from the inference process, containing parameter samples from the inference process, the maximum likelihood parameterisation, likelihood samples, and the sampling times.
#' @export
HyperTraPS <- function(obs, initialstates = NULL, priors = NULL, starttimes = NULL, endtimes = NULL, length = 3L, kernel = 5L, samplegap = -1L, losses = 0L, apm_type = 0L, sa = 0L, sgd = 0L, sgd_scale = 0.01, seed = 1L, outputinput = 0L, regularise = 0L, penalty = 0L, lasso = 0L, model = 2L, pli = 0L, walkers = 200L, full_analysis = 1L, limited_output = 0L, output_transitions = 1L, samples_per_row = 10L, featurenames = NULL) {
    .Call('_hypertrapsct_HyperTraPS', PACKAGE = 'hypertrapsct', obs, initialstates, priors, starttimes, endtimes, length, kernel, samplegap, losses, apm_type, sa, sgd, sgd_scale, seed, outputinput, regularise, penalty, lasso, model, pli, walkers, full_analysis, limited_output, output_transitions, samples_per_row, featurenames)
}

#' Extracts information from HyperTraPS-related posterior samples
#'
#' @param L List output from HyperTraPS, containing posterior samples
#' @return Named list containing summary data for feature acquisition ordering ("bubbles"), time histograms, sampled accumulation routes, and timings of these sampled routes.
#' @export
PosteriorAnalysis <- function(L, featurenames = NULL, use_regularised = 0L, limited_output = 0L, samples_per_row = 10L) {
    .Call('_hypertrapsct_PosteriorAnalysis', PACKAGE = 'hypertrapsct', L, featurenames, use_regularised, limited_output, samples_per_row)
}

